/**
 * @file calibration_correction.cpp
 * @brief Extract the actual kinematic parameters of a connected Flexiv robot into a
 * kinematics YAML file that flexiv_description can load.
 * @copyright Copyright (C) 2016-2025 Flexiv Ltd. All Rights Reserved.
 */

#include <flexiv/rdk/model.hpp>
#include <flexiv/rdk/robot.hpp>

#include <ament_index_cpp/get_package_share_directory.hpp>
#include <rclcpp/rclcpp.hpp>

#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

namespace {

namespace fs = std::filesystem;

bool IsUnder(const fs::path& path, const fs::path& root)
{
    auto p = path.begin();
    auto r = root.begin();
    for (; r != root.end(); ++p, ++r) {
        if (p == path.end() || *p != *r) {
            return false;
        }
    }
    return true;
}

/** Append the provenance of the sync. Must run after the sync, which rewrites the file. */
void AppendMetadata(const fs::path& target, const flexiv::rdk::RobotInfo& info, size_t joints)
{
    std::ofstream out(target, std::ios::app);
    if (!out) {
        throw std::runtime_error("failed to open " + target.string() + " for appending metadata");
    }
    out << "\n# Generated by flexiv_calibration. Do not edit by hand.\n"
        << "calibration_metadata:\n"
        << "  robot_sn: \"" << info.serial_num << "\"\n"
        << "  model_name: \"" << info.model_name << "\"\n"
        << "  robot_software_ver: \"" << info.software_ver << "\"\n"
        << "  joints_synced: " << joints << "\n";
}

} /* namespace */

int main(int argc, char** argv)
{
    rclcpp::init(argc, argv);
    auto node = std::make_shared<rclcpp::Node>("calibration_correction");
    const auto logger = node->get_logger();

    const auto robot_sn = node->declare_parameter<std::string>("robot_sn", "");
    const auto target_filename = node->declare_parameter<std::string>("target_filename", "");
    auto robot_type = node->declare_parameter<std::string>("robot_type", "");
    auto template_filename = node->declare_parameter<std::string>("template_filename", "");
    const auto overwrite = node->declare_parameter<bool>("overwrite", false);
    const auto whitelist = node->declare_parameter<std::vector<std::string>>(
        "network_interface_whitelist", std::vector<std::string>{});

    if (robot_sn.empty()) {
        RCLCPP_ERROR(logger, "Parameter [robot_sn] is required, e.g. Rizon4s-123456");
        return 1;
    }
    if (target_filename.empty()) {
        RCLCPP_ERROR(logger, "Parameter [target_filename] is required");
        return 1;
    }

    const fs::path target = fs::absolute(target_filename);
    if (fs::exists(target) && !overwrite) {
        RCLCPP_ERROR(logger, "[%s] already exists. Pass overwrite:=true to replace it",
            target.c_str());
        return 1;
    }

    // The sync rewrites the file in place, so writing into flexiv_description would mutate the
    // shipped defaults. Under --symlink-install the installed files point back at the source
    // checkout, so guard both trees. package.xml is symlinked and reveals the source one.
    const fs::path description_dir
        = ament_index_cpp::get_package_share_directory("flexiv_description");
    const fs::path canonical_target = fs::weakly_canonical(target);
    for (const auto& forbidden : {fs::weakly_canonical(description_dir),
             fs::weakly_canonical(description_dir / "package.xml").parent_path()}) {
        if (IsUnder(canonical_target, forbidden)) {
            RCLCPP_ERROR(logger,
                "Refusing to write into flexiv_description [%s]. Choose a target outside it",
                forbidden.c_str());
            return 1;
        }
    }

    try {
        RCLCPP_INFO(logger, "Connecting to robot [%s]...", robot_sn.c_str());
        flexiv::rdk::Robot robot(robot_sn, whitelist);
        const auto info = robot.info();
        RCLCPP_INFO(logger, "Connected to [%s], model [%s], software [%s], license [%s]",
            info.serial_num.c_str(), info.model_name.c_str(), info.software_ver.c_str(),
            info.license_type.c_str());

        if (robot_type.empty()) {
            robot_type = info.model_name;
        }

        if (template_filename.empty()) {
            template_filename
                = (description_dir / "config" / robot_type / "default_kinematics.yaml").string();
        }
        const fs::path tmpl = fs::path(template_filename);
        if (!fs::is_regular_file(tmpl)) {
            RCLCPP_ERROR(logger,
                "Template [%s] does not exist. Set [robot_type] to a robot type that "
                "flexiv_description ships a config for, or set [template_filename] explicitly",
                tmpl.c_str());
            return 1;
        }

        // For a template given explicitly, which may sit outside flexiv_description.
        const fs::path tmpl_dir = fs::weakly_canonical(tmpl).parent_path();
        if (IsUnder(canonical_target, tmpl_dir)) {
            RCLCPP_ERROR(logger,
                "Refusing to write into the template directory [%s]. Choose a target outside it",
                tmpl_dir.c_str());
            return 1;
        }

        if (target.has_parent_path()) {
            fs::create_directories(target.parent_path());
        }
        fs::copy_file(tmpl, target, fs::copy_options::overwrite_existing);

        flexiv::rdk::Model model(robot);
        const size_t synced = model.SyncKinematicsYAML(target.string());
        if (synced < info.DoF_m) {
            RCLCPP_WARN(logger,
                "Only %zu of %zu joints were synced. [%s] now mixes measured and nominal values",
                synced, info.DoF_m, target.c_str());
        }

        AppendMetadata(target, info, synced);
        RCLCPP_INFO(logger, "Synced %zu joints of [%s] into [%s]", synced, info.serial_num.c_str(),
            target.c_str());
    } catch (const std::invalid_argument& e) {
        RCLCPP_ERROR(logger, "%s", e.what());
        return 1;
    } catch (const std::logic_error& e) {
        RCLCPP_ERROR(logger,
            "%s. Reading kinematic parameters requires an RDK professional license", e.what());
        return 1;
    } catch (const std::exception& e) {
        RCLCPP_ERROR(logger, "%s", e.what());
        return 1;
    }

    rclcpp::shutdown();
    return 0;
}
