/**
 * @file calibration_correction.cpp
 * @brief Sync the actual kinematic parameters of a connected Flexiv robot into a kinematics
 * YAML file that flexiv_description loads.
 * @copyright Copyright (C) 2016-2025 Flexiv Ltd. All Rights Reserved.
 */

#include <flexiv/rdk/model.hpp>
#include <flexiv/rdk/robot.hpp>

#include <ament_index_cpp/get_package_share_directory.hpp>
#include <rclcpp/rclcpp.hpp>

#include <cctype>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace {

namespace fs = std::filesystem;

constexpr char kMetadataKey[] = "calibration_metadata:";
constexpr char kMetadataMarker[] = "# Generated by flexiv_calibration.";

/**
 * @brief Remove every metadata block an earlier run left behind. The sync rewrites the file
 * through a YAML round trip that keeps mappings but drops comments, so the block has to be
 * found by its key; anchoring on the comment above it would miss and the blocks would pile up.
 */
std::string StripMetadata(const std::string& content)
{
    std::istringstream in(content);
    std::string line;
    std::string out;
    bool in_block = false;

    while (std::getline(in, line)) {
        if (in_block) {
            // The block ends at the next line starting in column 0.
            if (line.empty() || std::isspace(static_cast<unsigned char>(line.front()))) {
                continue;
            }
            in_block = false;
        }
        if (line.rfind(kMetadataKey, 0) == 0) {
            in_block = true;
            continue;
        }
        if (line.rfind(kMetadataMarker, 0) == 0) {
            continue;
        }
        out += line;
        out += '\n';
    }
    return out;
}

/** Removes the temporary file unless the sync ran to completion. */
struct TempFile
{
    explicit TempFile(fs::path p)
    : path(std::move(p))
    {
    }
    ~TempFile()
    {
        std::error_code ec;
        fs::remove(path, ec);
    }
    fs::path path;
};

/**
 * @brief Check a template before it is used. The sync only fills keys the template already
 * lists, so the template decides which joints get measured values and an empty one syncs
 * nothing at all.
 */
bool TemplateIsUsable(const fs::path& tmpl, const rclcpp::Logger& logger)
{
    if (!fs::is_regular_file(tmpl)) {
        RCLCPP_ERROR(logger,
            "Template [%s] does not exist. Set [robot_type] to a robot type that "
            "flexiv_description ships a config for, or set [template_filename] explicitly",
            tmpl.c_str());
        return false;
    }
    if (fs::file_size(tmpl) == 0) {
        RCLCPP_ERROR(
            logger, "Template [%s] is empty. It must list the joints to sync", tmpl.c_str());
        return false;
    }
    return true;
}

/**
 * @brief Record which robot the parameters came from. Rewrites any block from an earlier run so
 * that repeated syncs of the same file do not stack up.
 */
void WriteMetadata(const fs::path& file, const flexiv::rdk::RobotInfo& info, size_t joints)
{
    std::string content;
    {
        std::ifstream in(file);
        std::stringstream buffer;
        buffer << in.rdbuf();
        content = buffer.str();
    }

    content = StripMetadata(content);
    while (!content.empty() && content.back() == '\n') {
        content.pop_back();
    }

    std::ofstream out(file, std::ios::trunc);
    if (!out) {
        throw std::runtime_error("Failed to open " + file.string() + " to write metadata");
    }
    out << content << "\n\n"
        << kMetadataMarker << " Do not edit by hand.\n"
        << "calibration_metadata:\n"
        << "  robot_sn: \"" << info.serial_num << "\"\n"
        << "  model_name: \"" << info.model_name << "\"\n"
        << "  robot_software_ver: \"" << info.software_ver << "\"\n"
        << "  joints_synced: " << joints << "\n";
}

} /* namespace */

int main(int argc, char** argv)
{
    rclcpp::init(argc, argv);
    auto node = std::make_shared<rclcpp::Node>("calibration_correction");
    const auto logger = node->get_logger();

    const auto robot_sn = node->declare_parameter<std::string>("robot_sn", "");
    const auto target_filename = node->declare_parameter<std::string>("target_filename", "");
    auto robot_type = node->declare_parameter<std::string>("robot_type", "");
    auto template_filename = node->declare_parameter<std::string>("template_filename", "");
    const auto whitelist = node->declare_parameter<std::vector<std::string>>(
        "network_interface_whitelist", std::vector<std::string> {});

    if (robot_sn.empty()) {
        RCLCPP_ERROR(logger, "Parameter [robot_sn] is required, e.g. Rizon4s-123456");
        return 1;
    }

    try {
        const fs::path description_dir
            = ament_index_cpp::get_package_share_directory("flexiv_description");
        const auto default_template = [&](const std::string& type) {
            return (description_dir / "config" / type / "default_kinematics.yaml").string();
        };

        // Resolve the template as early as the inputs allow, so a bad one is reported without
        // first waiting on the robot. Only an unset robot_type has to wait for the robot to
        // name itself.
        if (template_filename.empty() && !robot_type.empty()) {
            template_filename = default_template(robot_type);
        }
        if (!template_filename.empty() && !TemplateIsUsable(template_filename, logger)) {
            return 1;
        }

        RCLCPP_INFO(logger, "Connecting to robot [%s]...", robot_sn.c_str());
        flexiv::rdk::Robot robot(robot_sn, whitelist);
        const auto info = robot.info();
        RCLCPP_INFO(logger, "Connected to [%s], model [%s], software [%s], license [%s]",
            info.serial_num.c_str(), info.model_name.c_str(), info.software_ver.c_str(),
            info.license_type.c_str());

        if (robot_type.empty()) {
            robot_type = info.model_name;
        }
        if (template_filename.empty()) {
            template_filename = default_template(robot_type);
            if (!TemplateIsUsable(template_filename, logger)) {
                return 1;
            }
        }
        const fs::path tmpl = fs::path(template_filename);

        // Default to updating the template itself, which is what flexiv_description loads unless
        // a launch file points it elsewhere. Resolve symlinks so that a --symlink-install
        // workspace updates the source file rather than replacing the link with a copy.
        const fs::path dest
            = fs::weakly_canonical(target_filename.empty() ? tmpl : fs::absolute(target_filename));
        if (dest.has_parent_path()) {
            fs::create_directories(dest.parent_path());
        }

        // Sync a copy and move it into place, so a failed sync cannot leave a half-written file.
        TempFile tmp(dest.parent_path() / (dest.filename().string() + ".flexiv_calibration.tmp"));
        fs::copy_file(tmpl, tmp.path, fs::copy_options::overwrite_existing);

        flexiv::rdk::Model model(robot);
        const size_t synced = model.SyncKinematicsYAML(tmp.path.string());
        // Nothing matched, so the result would carry nominal values while looking calibrated.
        // Leave [dest] alone; the temporary file is discarded on the way out.
        if (synced == 0) {
            RCLCPP_ERROR(logger,
                "Synced 0 joints, so [%s] was not written. The sync only fills keys already "
                "present in the template [%s] -- check that it lists this robot's joints",
                dest.c_str(), tmpl.c_str());
            return 1;
        }
        if (synced < info.DoF_m) {
            RCLCPP_WARN(logger,
                "Only %zu of %zu joints were synced. [%s] now mixes measured and nominal values",
                synced, info.DoF_m, dest.c_str());
        }

        WriteMetadata(tmp.path, info, synced);
        fs::rename(tmp.path, dest);

        RCLCPP_INFO(logger, "Synced %zu joints of [%s] into [%s]", synced, info.serial_num.c_str(),
            dest.c_str());
        if (dest == fs::weakly_canonical(tmpl)) {
            RCLCPP_INFO(logger,
                "This is flexiv_description's shipped default for [%s], so every launch file "
                "picks it up with no extra argument. Expect it to show as a local change in "
                "flexiv_description",
                robot_type.c_str());
        }
    } catch (const std::invalid_argument& e) {
        RCLCPP_ERROR(logger, "%s", e.what());
        return 1;
    } catch (const std::logic_error& e) {
        RCLCPP_ERROR(logger,
            "%s. Reading kinematic parameters requires an RDK professional license", e.what());
        return 1;
    } catch (const std::exception& e) {
        RCLCPP_ERROR(logger, "%s", e.what());
        return 1;
    }

    rclcpp::shutdown();
    return 0;
}
