int8 MODE_UNKNOWN                          = 0
int8 MODE_IDLE                             = 1
int8 MODE_RT_JOINT_TORQUE                  = 2
int8 MODE_RT_JOINT_IMPEDANCE               = 3
int8 MODE_NRT_JOINT_IMPEDANCE              = 4
int8 MODE_RT_JOINT_POSITION                = 5
int8 MODE_NRT_JOINT_POSITION               = 6
int8 MODE_NRT_PLAN_EXECUTION               = 7
int8 MODE_NRT_PRIMITIVE_EXECUTION          = 8
int8 MODE_RT_CARTESIAN_MOTION_FORCE        = 9
int8 MODE_NRT_CARTESIAN_MOTION_FORCE       = 10
int8 MODE_NRT_SUPER_PRIMITIVE              = 11

int8 mode
