int8 MODE_UNKNOWN                          = -1
int8 MODE_IDLE                             = 0
int8 MODE_RT_JOINT_TORQUE                  = 1
int8 MODE_RT_JOINT_POSITION                = 2
int8 MODE_NRT_JOINT_POSITION               = 3
int8 MODE_NRT_PLAN_EXECUTION               = 4
int8 MODE_NRT_PRIMITIVE_EXECUTION          = 5
int8 MODE_RT_CARTESIAN_MOTION_FORCE_BASE   = 6
int8 MODE_RT_CARTESIAN_MOTION_FORCE_TCP    = 7
int8 MODE_NRT_CARTESIAN_MOTION_FORCE_BASE  = 8
int8 MODE_NRT_CARTESIAN_MOTION_FORCE_TCP   = 9

int8 mode