controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    joint_impedance_controller:
      type: flexiv_controllers/JointImpedanceController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    external_wrench_in_base_broadcaster:
      type: flexiv_controllers/ExternalTcpWrenchBroadcaster

    external_wrench_in_tcp_broadcaster:
      type: flexiv_controllers/ExternalTcpWrenchBroadcaster
    
    tcp_pose_state_broadcaster:
      type: flexiv_controllers/TcpPoseStateBroadcaster

    rizon_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: force_torque_sensor
    frame_id: flange

external_wrench_in_tcp_broadcaster:
  ros__parameters:
    sensor_name: external_wrench_in_tcp
    frame_id: flange
    topic_name: external_wrench_in_tcp

external_wrench_in_base_broadcaster:
  ros__parameters:
    sensor_name: external_wrench_in_base
    frame_id: base_link
    topic_name: external_wrench_in_base

tcp_pose_state_broadcaster:
  ros__parameters:
    sensor_name: tcp_pose
    frame_id: flange
    topic_name: tcp_pose

forward_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7

joint_impedance_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    k_p: [3000.0, 3000.0, 800.0, 800.0, 200.0, 200.0, 200.0]
    k_d: [80.0, 80.0, 40.0, 40.0, 8.0, 8.0, 8.0]

rizon_arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
