sine_sweep_impedance_controller:
  ros__parameters:

    controller_name: "joint_impedance_controller"
    joints:
      - $(var robot_sn)_joint1
      - $(var robot_sn)_joint2
      - $(var robot_sn)_joint3
      - $(var robot_sn)_joint4
      - $(var robot_sn)_joint5
      - $(var robot_sn)_joint6
      - $(var robot_sn)_joint7
    wait_sec_between_publish: 0.001
    speed_scaling: 1.0
