controller_names:
  - rizon_arm_controller
  - flexiv_gripper_node

rizon_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - $(var robot_sn)_joint1
    - $(var robot_sn)_joint2
    - $(var robot_sn)_joint3
    - $(var robot_sn)_joint4
    - $(var robot_sn)_joint5
    - $(var robot_sn)_joint6
    - $(var robot_sn)_joint7

flexiv_gripper_node:
  action_ns: gripper_action
  type: GripperCommand
  default: true
  joints:
    - $(var robot_sn)_finger_width_joint
