controller_names:
  - left_flexiv_arm_controller
  - right_flexiv_arm_controller
  - left_flexiv_gripper_node
  - right_flexiv_gripper_node

left_flexiv_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - left_$(var robot_sn)_joint1
    - left_$(var robot_sn)_joint2
    - left_$(var robot_sn)_joint3
    - left_$(var robot_sn)_joint4
    - left_$(var robot_sn)_joint5
    - left_$(var robot_sn)_joint6
    - left_$(var robot_sn)_joint7

right_flexiv_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - right_$(var robot_sn)_joint1
    - right_$(var robot_sn)_joint2
    - right_$(var robot_sn)_joint3
    - right_$(var robot_sn)_joint4
    - right_$(var robot_sn)_joint5
    - right_$(var robot_sn)_joint6
    - right_$(var robot_sn)_joint7

left_flexiv_gripper_node:
  action_ns: gripper_action
  type: GripperCommand
  default: true
  joints:
    - left_$(var robot_sn)_finger_width_joint

right_flexiv_gripper_node:
  action_ns: gripper_action
  type: GripperCommand
  default: true
  joints:
    - right_$(var robot_sn)_finger_width_joint
