name: Foxy Binary Build

on:
  push:
    branches:
      - main
      - foxy
  pull_request:
    branches:
      - main
      - foxy

jobs:
  foxy_binary:
    name: Foxy binary job
    runs-on: ubuntu-20.04
    container:
      image: osrf/ros:foxy-desktop
    strategy:
      fail-fast: false
    env:
      ROS_DISTRO: foxy
    steps:
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: ${{ env.ROS_DISTRO }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and run tests
        id: action-ros-ci
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: ${{ env.ROS_DISTRO }}
          package-name: |
            flexiv_bringup
            flexiv_controllers
            flexiv_description
            flexiv_hardware
            flexiv_moveit_config
            flexiv_msgs
            flexiv_test_nodes
          skip-tests: true
