name: Jazzy Binary Build

on:
  push:
    branches:
      - jazzy
  pull_request:
    branches:
      - jazzy
      - release/jazzy-*

jobs:
  jazzy_binary:
    name: Jazzy binary job
    runs-on: ubuntu-24.04
    container:
      image: osrf/ros:jazzy-desktop
    strategy:
      fail-fast: false
    env:
      ROS_DISTRO: jazzy
      RDK_INSTALL_PREFIX: ${{ github.workspace }}/rdk_install
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          wget \
          libeigen3-dev \
          ros-jazzy-control-toolbox \
          ros-jazzy-hardware-interface \
          ros-jazzy-joint-state-publisher \
          ros-jazzy-joint-state-publisher-gui \
          ros-jazzy-moveit \
          ros-jazzy-realtime-tools \
          ros-jazzy-robot-state-publisher \
          ros-jazzy-ros2-control \
          ros-jazzy-ros2-controllers \
          ros-jazzy-rmw-cyclonedds-cpp \
          ros-jazzy-test-msgs \
          ros-jazzy-tinyxml2-vendor \
          ros-jazzy-xacro
      - name: Build and install flexiv_rdk
        shell: bash
        run: |
          git clone --branch v2.0 --depth 1 https://github.com/flexivrobotics/flexiv_rdk.git
          cd flexiv_rdk/thirdparty
          bash build_and_install_dependencies.sh "${RDK_INSTALL_PREFIX}"
          cd ..
          mkdir -p build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX="${RDK_INSTALL_PREFIX}"
          make install
      - name: Verify flexiv_rdk install
        shell: bash
        run: |
          test -f "${RDK_INSTALL_PREFIX}/lib/cmake/flexiv_rdk/flexiv_rdk-config.cmake"
      - name: Build workspace
        id: action-ros-ci
        uses: ros-tooling/action-ros-ci@v0.4
        env:
          CMAKE_PREFIX_PATH: ${{ env.RDK_INSTALL_PREFIX }}
          RMW_IMPLEMENTATION: ${{ env.RMW_IMPLEMENTATION }}
        with:
          target-ros2-distro: ${{ env.ROS_DISTRO }}
          vcs-repo-file-url: ${{ github.workspace }}/flexiv.jazzy.repos
          package-name: |
            flexiv_bringup
            flexiv_gripper
            flexiv_hardware
            flexiv_moveit_config
            flexiv_msgs
            flexiv_robot_states_broadcaster
            flexiv_test_nodes
            gpio_controller
          extra-cmake-args: -DCMAKE_PREFIX_PATH=${{ env.RDK_INSTALL_PREFIX }}
          skip-tests: true
