name: Jazzy Binary Build

on:
  push:
    branches:
      - jazzy-v1
      - jazzy-v2
  pull_request:
    branches:
      - jazzy-v1
      - jazzy-v2
      - release/jazzy-*

jobs:
  jazzy_binary:
    name: Jazzy binary job
    runs-on: ubuntu-24.04
    container:
      image: osrf/ros:jazzy-desktop
    strategy:
      fail-fast: false
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      ROS_DISTRO: jazzy
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          wget \
          libeigen3-dev \
          ros-jazzy-control-toolbox \
          ros-jazzy-hardware-interface \
          ros-jazzy-joint-state-publisher \
          ros-jazzy-joint-state-publisher-gui \
          ros-jazzy-moveit \
          ros-jazzy-realtime-tools \
          ros-jazzy-robot-state-publisher \
          ros-jazzy-ros2-control \
          ros-jazzy-ros2-controllers \
          ros-jazzy-test-msgs \
          ros-jazzy-tinyxml2-vendor \
          ros-jazzy-xacro
      - name: Build and install flexiv_rdk
        shell: bash
        run: |
          git clone --branch v1.9.1 --depth 1 https://github.com/flexivrobotics/flexiv_rdk.git
          cd flexiv_rdk/thirdparty
          source /opt/ros/jazzy/setup.bash
          bash build_and_install_dependencies_not_in_ros2.sh ~/flexiv_install 8
          cd ..
          mkdir -p build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=~/flexiv_install -DRDK_SUPPORT_ROS2_JAZZY=ON
          make install
      - name: Build and install flexiv_drdk
        shell: bash
        run: |
          git clone --branch v1.2.1 --depth 1 https://github.com/flexivrobotics/flexiv_drdk.git
          cd flexiv_drdk/thirdparty
          source /opt/ros/jazzy/setup.bash
          bash build_and_install_dependencies.sh ~/flexiv_install 8 --skip-rdk
          cd ..
          mkdir -p build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=~/flexiv_install -DDRDK_SUPPORT_ROS2_JAZZY=ON
          make install
      - name: Build and run tests
        id: action-ros-ci
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: ${{ env.ROS_DISTRO }}
          vcs-repo-file-url: ${{ github.workspace }}/flexiv.jazzy.repos
          package-name: |
            flexiv_bringup
            flexiv_gripper
            flexiv_hardware
            flexiv_moveit_config
            flexiv_msgs
            flexiv_robot_states_broadcaster
            flexiv_test_nodes
            gpio_controller
          colcon-defaults: |
            {
              "build": {
                "cmake-args": [
                    "-DCMAKE_PREFIX_PATH=~/flexiv_install"
                ]
              }
            }
          skip-tests: true
